import type { MacroAction } from "@browser-mcp/shared";
import { getUniqueSelector, getXPath } from "./dom-utils.js";

let recording = false;
let actions: MacroAction[] = [];
let listenersAttached = false;

function push(action: Omit<MacroAction, "timestamp" | "url">): void {
  if (!recording) return;
  actions.push({
    ...action,
    timestamp: Date.now(),
    url: location.href,
  });
}

function onClick(e: MouseEvent): void {
  const t = e.target as Element | null;
  if (!t || !(t instanceof Element)) return;
  if (t.closest?.("#__browser_mcp_som_overlay__")) return;
  push({
    type: "click",
    selector: getUniqueSelector(t),
    xpath: getXPath(t),
    text: (t.textContent || "").trim().slice(0, 80),
    coordinates: { x: e.clientX, y: e.clientY },
    semantic: `Click on ${t.tagName.toLowerCase()}${t.id ? "#" + t.id : ""} "${(t.textContent || "").trim().slice(0, 40)}"`,
  });
}

function onInput(e: Event): void {
  const t = e.target as HTMLInputElement | HTMLTextAreaElement | null;
  if (!t || !(t instanceof Element)) return;
  push({
    type: "type",
    selector: getUniqueSelector(t),
    xpath: getXPath(t),
    value: "value" in t ? String(t.value).slice(0, 200) : undefined,
    semantic: `Type into ${t.tagName.toLowerCase()}${t.getAttribute("name") ? `[name=${t.getAttribute("name")}]` : ""}`,
  });
}

function onKeydown(e: KeyboardEvent): void {
  if (["Enter", "Tab", "Escape"].includes(e.key) || e.ctrlKey || e.metaKey) {
    const t = e.target as Element | null;
    push({
      type: "keydown",
      key: e.key,
      selector: t instanceof Element ? getUniqueSelector(t) : undefined,
      semantic: `Press key ${e.key}`,
    });
  }
}

function onChange(e: Event): void {
  const t = e.target as HTMLSelectElement | HTMLInputElement | null;
  if (!t) return;
  push({
    type: "change",
    selector: getUniqueSelector(t),
    value: "value" in t ? String(t.value) : undefined,
    semantic: `Change ${t.tagName.toLowerCase()} to "${(t as HTMLInputElement).value}"`,
  });
}

function onScroll(): void {
  // debounce via last action type
  const last = actions[actions.length - 1];
  if (last?.type === "scroll" && Date.now() - last.timestamp < 400) {
    last.coordinates = { x: window.scrollX, y: window.scrollY };
    last.timestamp = Date.now();
    return;
  }
  push({
    type: "scroll",
    coordinates: { x: window.scrollX, y: window.scrollY },
    semantic: `Scroll to ${window.scrollY}`,
  });
}

function attach(): void {
  if (listenersAttached) return;
  document.addEventListener("click", onClick, true);
  document.addEventListener("input", onInput, true);
  document.addEventListener("keydown", onKeydown, true);
  document.addEventListener("change", onChange, true);
  window.addEventListener("scroll", onScroll, { passive: true });
  listenersAttached = true;
}

function detach(): void {
  if (!listenersAttached) return;
  document.removeEventListener("click", onClick, true);
  document.removeEventListener("input", onInput, true);
  document.removeEventListener("keydown", onKeydown, true);
  document.removeEventListener("change", onChange, true);
  window.removeEventListener("scroll", onScroll);
  listenersAttached = false;
}

export function startRecording(): { ok: true } {
  recording = true;
  actions = [];
  attach();
  push({
    type: "navigate",
    semantic: `Start recording on ${location.href}`,
  });
  return { ok: true };
}

export function stopRecording(): MacroAction[] {
  recording = false;
  detach();
  const result = [...actions];
  actions = [];
  return result;
}

export function isRecording(): boolean {
  return recording;
}

export function generateReplayScript(actions: MacroAction[]): string {
  const lines = [
    "// Generated by Browser MCP macro recorder",
    "async function runMacro(page, vars = {}) {",
  ];
  let lastUrl = "";
  for (const a of actions) {
    if (a.type === "navigate" && a.url && a.url !== lastUrl) {
      lines.push(`  await page.goto(${JSON.stringify(a.url)});`);
      lastUrl = a.url;
    } else if (a.type === "click" && a.selector) {
      lines.push(
        `  await page.click(${JSON.stringify(a.selector)}); // ${a.semantic ?? ""}`,
      );
    } else if (a.type === "type" && a.selector) {
      const val = a.value ?? "";
      lines.push(
        `  await page.fill(${JSON.stringify(a.selector)}, ${JSON.stringify(val)});`,
      );
    } else if (a.type === "keydown" && a.key) {
      lines.push(`  await page.keyboard.press(${JSON.stringify(a.key)});`);
    } else if (a.type === "scroll" && a.coordinates) {
      lines.push(
        `  await page.evaluate((y) => window.scrollTo(0, y), ${a.coordinates.y});`,
      );
    } else if (a.type === "change" && a.selector) {
      lines.push(
        `  await page.selectOption(${JSON.stringify(a.selector)}, ${JSON.stringify(a.value ?? "")}).catch(() => page.fill(${JSON.stringify(a.selector)}, ${JSON.stringify(a.value ?? "")}));`,
      );
    }
  }
  lines.push("  return { ok: true };", "}");
  return lines.join("\n");
}
